# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
---
blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://pcb.id.au/security-report
    about: Report suspected security vulnerabilities here.